project:
  type: book
  output-dir: docs
bibliography: weighting_refs.bib
nocite: |
  @*
jupyter: nbstata

execute:
  warning: false
  message: false
  freeze: false

book:
  title: "Statistical inference  with weights and survey design variables"
  subtitle: Practical guidelines using  UKDS datasets
#  downloads: [pdf] ### Not working with diagrams currently
  chapters:
    - index.qmd
    - 01_Basics.qmd
    - 02_Design-Based_Inference.qmd
    - 03_Real_world.qmd
    - 04_Statistical_Inference.qmd
    - part: "5. Exercises"
      chapters:
        - 05_R.qmd
        - 06_SPSS.qmd
        - 07_Stata.qmd
    - 09_References.qmd
    - 08_Appendix.qmd

  sidebar:
    logo: "pics/UKDS_Logos_Col_Grey_300dpi.png"
    logo-href: https://ukdataservice.ac.uk
    logo-alt: "UKDS homepage"
    style: "floating"
    search: true
    title: " "
    

format:
    # html: 
      code-overflow: scroll
      code-line-numbers: true
      page-layout: full
      toc: true
      toc-location: right
      highlight-style: arrow-light
      smooth-scroll: true
      link-external-newwindow: true
      citations-hover: true
      footnotes-hover: true
      css: ukds_long.css

    # titlepage-pdf:
    #   titlepage: plain
    #   titlepage-geometry:
    #     - top=70mm
    #     - left=30mm
    #     - right=30mm
    #     - bottom=30mm
    #   titlepage-theme:
    #     logo-size: 3cm
    #     title-fontstyle: Huge
    #   titlepage-logo: "pics/UKDS_Logos_Col_Grey_300dpi.png"  
    #   documentclass: scrreport
    #   fig-width: 7
    #   papersize: A4
    #   include-in-header: preamble.tex
    #   geometry:
    #     - top=25mm
    #     - left=25mm
    #     - right=25mm
    #     - bottom=30mm


pdf-engine: lualatex




